export const ARCHELON_VERSION = process.env.REACT_APP_ARCHELON_VERSION;
export const PROJECT_BUILD = process.env.REACT_APP_PROJECT_BUILD;
export const ARCHELON_VERSION_TITLE = process.env.REACT_APP_ARCHELON_VERSION_TITLE;
export const ROW_PER_PAGE = 15;
